# Generated by Django 5.2.17 on 2026-09-22 07:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=160)),
                ('qualification', models.CharField(help_text='e.g. BSc Computer Science', max_length=160)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=220)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=140)),
                ('company', models.CharField(max_length=140)),
                ('company_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave empty if this is current.', null=True)),
                ('description', models.TextField(blank=True, help_text='One bullet per line.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Experience',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('headline', models.CharField(help_text="One line under your name, e.g. 'Backend developer, Kathmandu'.", max_length=160)),
                ('bio', models.TextField(help_text='A few short paragraphs. Blank lines start new paragraphs.')),
                ('location', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('avatar', models.ImageField(blank=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, upload_to='resume/')),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True, verbose_name='X / Twitter URL')),
                ('website_url', models.URLField(blank=True)),
                ('open_to_work', models.BooleanField(default=True, help_text="Shows an 'open to work' note in the sidebar.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('summary', models.CharField(help_text='One sentence shown in the project list.', max_length=220)),
                ('description', models.TextField(help_text='The full write-up. Blank lines start new paragraphs.')),
                ('tech_stack', models.CharField(blank=True, help_text='Comma separated, e.g. Django, Postgres, HTMX', max_length=240)),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('live_url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('role', models.CharField(blank=True, help_text='e.g. Solo build, Team of 4', max_length=120)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured projects show on the home page.')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-completed_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('language', 'Languages'), ('framework', 'Frameworks'), ('database', 'Databases'), ('tool', 'Tools'), ('other', 'Other')], default='other', max_length=20)),
                ('proficiency', models.PositiveSmallIntegerField(default=70, help_text='0–100. Drawn as a bar on the home page.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers come first.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
